# Site settings
title: Kerri Shotts
email: kerrishotts@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just some thoughts and mind dumps that might be interesting!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: photokandy
github_username:  kerrishotts
highlighter: pygments
# Build settings
markdown: kramdown
